-- CRIAR TABELA TEMPORARIA 
CREATE TABLE TMP_MUDANCA_DADOS_BANCO
(COD_VENDA VARCHAR(10),
PARCELA VARCHAR(5),
NOSSO_NUMERO VARCHAR(20),
COD_BARRAS VARCHAR(70))
--OBS :NESSE MOMENTO COMO A TABELA É TEMPORÁRIA NÃO ME PREOCUPEI COM OS TIPOS CORRETOS 

-- INSERT DE TITULOS NA TABELA TEMPORARIA MANUALMENTE HABILITANDO O FOR UPDATE, POSTERIORMENTE DEVERÁ SER AUTOMATIZADO
SELECT * FROM TMP_MUDANCA_DADOS_BANCO -- FOR UPDATE 

-- VINCULAÇÃO DE TABELA TEMPORARIA COM TABELA DO SISTEMA A FIM DE TRAZER OS 6.635 TITULOS DO BANCO
SELECT PR.VEN_CODIGO_VENDA,
       PR.NUM_PARCELA,
       PR.VALOR,
       PR.NOSSO_NUMERO,
       PR.NUM_CODI_BARRAS,
       PR.NUMERO_COBR_PAG

FROM TB_TITULOS PR

WHERE PR.CODIGO_VENDA IN (SELECT K.COD_VENDA FROM TMP_MUDANCA_DADOS_BANCO K WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA) 

-- UPDATE DA TABELA MANUALMENTE
UPDATE TB_TITULOS PR

SET PR.NOSSO_NUMERO = (SELECT K.NOSSO_NUMERO FROM TMP_MUDANCA_DADOS_BANCO K WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA),
    PR.NUM_CODI_BARRAS = (SELECT K.COD_BARRAS FROM TMP_MUDANCA_DADOS_BANCO K WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA)

WHERE PR.VEN_CODIGO_VENDA IN (SELECT K.COD_VENDA FROM TMP_MUDANCA_DADOS_BANCO K WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA)
  AND PR.NUM_PARCELA =  (SELECT K.PARCELA FROM TMP_MUDANCA_DADOS_BANCO K WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA AND K.PARCELA = PR.NUM_PARCELA)
  
COMMIT; --FINALIZANDO COM O COMMIT PARA QUE AS ALTERAÇÕES SEJAM SALVAS NO BANCO DE DADOS 
 
-- CRIAÇÃO DE TABELA TEMPORÁRIA QUE SERVIRÁ COMO LOG DE UPDATE DE TÍTULOS PARA CONSULTA POSTERIOR
 CREATE TABLE TMP_LOG_TITULOS_BANCO
 ( 
  COD_TITULO VARCHAR(15),
  PARCELA VARCHAR(5),
  NOSSO_NUMERO VARCHAR(30),
  CODIGO_BARRAS VARCHAR(70),
  DATA_INSERCAO DATE 
 ) --OBS :NESSE MOMENTO COMO A TABELA É TEMPORÁRIA NÃO ME PREOCUPEI COM OS TIPOS CORRETOS 

-- INSERT DOS DADOS NA TABELA TEMPORARIA
   INSERT INTO TMP_LOG_TITULOS_BANCO (COD_TITULO, PARCELA, NOSSO_NUMERO, CODIGO_BARRAS, DATA_INSERCAO )
    SELECT 
        K.COD_VENDA AS COD_TITULO,
        K.PARCELA,
        K.NOSSO_NUMERO,
        K.COD_BARRAS,
        SYSDATE --DATA ATUAL
    FROM 
        TMP_MUDANCA_DADOS_BANCO K
    WHERE K.COD_VENDA NOT IN (SELECT L.COD_TITULO FROM TMP_LOG_TITULOS_BANCO L); -- INSERIR DESDE QUE JÁ NÃO ESTEJA NA TABELA NO LOG, PARA NÃO DUPLICAR OS TÍTULOS A CADA EXECUÇÃO   
    COMMIT; 

-- LIMPARA OS DADOS DA TABELA
DELETE TMP_MUDANCA_DADOS_BANCO; -- OU SEJA, APÓS O UPDATE SER REALIZADO OS DADOS DA TABELA SERÃO LIMPOS PARA QUE A TABELA FIQUE PRONTA PARA A INSERÇÃO DE NOVOS DADOS

-- SELECT PARA VERIFICAR SE OS TÍTULOS ENTRARAM NA TABELA
SELECT * FROM TMP_LOG_TITULOS_BANCO 

 -- INICIO DA PROCEDURE
CREATE OR REPLACE PROCEDURE ATUALIZARTITULOSBANCO IS 
BEGIN
    -- ATUALIZA OS CAMPOS NOSSO_NUMERO E NUM_CODI_BARRAS NA TABELA TB_TITULOS
    UPDATE TB_TITULOS PR
    SET 
        PR.NOSSO_NUMERO = (SELECT K.NOSSO_NUMERO 
                                  FROM TMP_MUDANCA_DADOS_BANCO K 
                                  WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA),
        PR.NUM_CODI_BARRAS = (SELECT K.COD_BARRAS 
                                  FROM TMP_MUDANCA_DADOS_BANCO K 
                                  WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA)
    WHERE 
        PR.VEN_CODIGO_VENDA IN (SELECT K.COD_VENDA 
                                    FROM TMP_MUDANCA_DADOS_BANCO K 
                                    WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA)
        AND PR.NUM_PARCELA = (SELECT K.PARCELA 
                                  FROM TMP_MUDANCA_DADOS_BANCO K 
                                  WHERE K.COD_VENDA = PR.VEN_CODIGO_VENDA 
                                    AND K.PARCELA = PR.NUM_PARCELA) 
    COMMIT; -- CONFIRMA A TRANSAÇÃO
    
    --- INSERT NA TABELA COMO LOG
     INSERT INTO TMP_LOG_TITULOS_BANCO (COD_TITULO, PARCELA, NOSSO_NUMERO, CODIGO_BARRAS, DATA_INSERCAO)
     SELECT 
        K.COD_VENDA AS COD_TITULO,
        K.PARCELA,
        K.NOSSO_NUMERO,
        K.COD_BARRAS,
        SYSDATE 
    FROM 
        TMP_MUDANCA_DADOS_BANCO K
    WHERE K.COD_VENDA NOT IN (SELECT L.COD_TITULO FROM TMP_LOG_TITULOS_BANCO L); -- INSERIR DESDE QUE JÁ NÃO ESTEJA NA TABELA NO LOG, PARA NÃO DUPLICAR OS TÍTULOS A CADA EXECUÇÃO   
    COMMIT; 
    
END ATUALIZARTITULOSBANCO;
--FIM DA PROCEDURE 

-- EXECUTAR A PROCEDURE
BEGIN 
ATUALIZARTITULOSBANCO; 
END; 
--FIM DA EXECUÇÃO  
